export const TEXTS =  {
    login : "Login",
    signUp: "SignUp",
    email : "Email",
    password : "Password",
    firstName : "First Name",
    userName : "Email",
    lastName : "last Name",
    error : "There is an error, try again",
    passwordHint: "8 character min. with a number, symbol, upper, lower case letter",
    confirmPassword: "Confirm Password",
    createNewAccountSuccessfully: "you successfully create new account",
    passwordsDidnnotMatch: "Those passwords didn't match.",
    insertCorrectMail: "Please Insert correct email.",
    passwordDescription: "Please insert at least 8 characters with at least one lower case letter.",
    insertOneLowerCaseLetter: "Please Insert at least one lower case letter.",
    insertCorrectName: "Please Insert Your Correct Name.",
    home: "Home Page",
    profile: "My Profile",
    logOut: "Log-Out"
}
